#!/bin/sh
# Stash (C) 2015-2020 Jeffrey E. Bedard

# Very simple symlink-based package manager

# Set to your desired package location. Install packages in individual
# prefixes within this directory.

# Configure example for gettext:
# ./configure --prefix=/opt/gettext-0.20.1; make; make install

# Trace execution.
#set -x

# Set this to where you wish to install packages in individual directories.
STASH=/opt
# Set this to the destination directory where symlinks should be made.
DEST=/usr/local

get_items()
{
    local PREV=$PWD # pushd/popd are bashisms
    local SRC=$STASH/"$1"
    if [ -d "$SRC" ]; then
        cd "$SRC"
        find . | cut -d. -f2- | cut -d/ -f2-
        cd $PREV
    fi
}
uninstall_package()
{
    local IFS=$'\n'
    for ARG in $@; do
        for ITEM in `get_items "$ARG"`; do
            if [ -L $DEST/"$ITEM" ]; then
                echo rm $DEST/"$ITEM"
                rm $DEST/"$ITEM"
            fi
        done
    done
}
install_package()
{
    local IFS=$'\n'
    for ARG in $@; do
        for ITEM in `get_items "$ARG"`; do
	    ITEM=`echo $ITEM | sed 's/\s/\\ /g'`
            if [ -d $STASH/$ARG/"$ITEM" ]; then
                mkdir -p $DEST/"$ITEM"
            else
                rm -f $DEST/"$ITEM" # Remove conflicts
                ln -sv $STASH/$ARG/"$ITEM" $DEST/"$ITEM"
            fi
        done
    done
}
build_install()
{
    local PREV=$PWD
    local SRCDIR=`tar xvf $1 | tail -n 1 | cut -d/ -f1`
    cd $SRCDIR
    ./configure --prefix=$STASH/$SRCDIR
    make -j8
    make install
    stash $SRCDIR
    cd $PREV
}
OPTSTRING="b:hlr:"
OPTIONS=`getopt -- $OPTSTRING "$@"` || exit 1
eval set -- "$OPTIONS"
while true; do
    case "$1" in
        -b) build_install $2; shift;;
        -h) echo "stash -[$OPTSTRING]"; shift;;
        -l) ls $STASH; shift;;
        -r) uninstall_package $2; shift 2;;
        --) shift; install_package $@; break;;
    esac
done
