#!/bin/sh
# Stash (C) 2015-2020 Jeffrey E. Bedard

# Very simple symlink-based package manager

# Set to your desired package location. Install packages in individual
# prefixes within this directory.

# Configure example for gettext:
# ./configure --prefix=/opt/gettext-0.20.1; make; make install

# Trace execution.
#set -x

# Set this to where you wish to install packages.
STASHDIR=/opt
# Set this to the destination directory where symlinks should be made.
PREFIX=/usr/local

get_items()
{
    PREV=$PWD # pushd/popd are bashisms
    SRC=$STASHDIR/"$1"
    if [ -d "$SRC" ]; then
        cd "$SRC"
        find . | cut -d. -f2- | cut -d/ -f2-
        cd $PREV
    fi
}
uninstall_package()
{
    for ARG in $@; do
        for ITEM in `get_items "$ARG"`; do
            if [ -L $PREFIX/"$ITEM" ]; then
                rm $PREFIX/"$ITEM"
            fi
        done
    done
}
install_package()
{
    for ARG in $@; do
        uninstall_package "$ARG"
        for ITEM in `get_items "$ARG"`; do
            if [ -d $PREFIX/"$ITEM" ]; then
                mkdir -p $PREFIX/"$ITEM"
            else
                ln -sf $STASHDIR/$ARG/"$ITEM" $PREFIX/"$ITEM"
            fi
        done
    done
}
OPTSTRING="hlr:"
OPTIONS=`getopt -- $OPTSTRING "$@"` || exit 1
eval set -- "$OPTIONS"
while true; do
    case "$1" in
        -h) echo "stash -[$OPTSTRING]"; shift;;
        -l) ls $STASHDIR; shift;;
        -r) uninstall_package $2; shift 2;;
        --) shift; install_package $@; break;;
    esac
done
