#!/bin/sh
# Stash (C) 2015-2020 Jeffrey E. Bedard

# Very simple symlink-based package manager

# Set to your desired package location. Install packages in individual
# prefixes within this directory.

# Configure example for gettext:
# ./configure --prefix=/opt/gettext-0.20.1; make; make install

# Trace execution.
#set -x

# Set this to where you wish to install packages.
STASHDIR=/opt
# Set this to the destination directory where symlinks should be made.
PREFIX=/usr/local

get_items()
{
    PREV=$PWD # pushd/popd are bashisms
    cd $STASHDIR/"$1"
    find . | cut -d. -f2- | cut -d/ -f2-
    cd $PREV
}
uninstall_package()
{
    for ARG in $@; do
        for ITEM in `get_items "$ARG"`; do
            if [ -f $PREFIX/"$ITEM" ]; then
                echo rm $PREFIX/"$ITEM"
                rm $PREFIX/"$ITEM"
            fi
        done
    done
}
install_package()
{
    for ARG in $@; do
        uninstall_package "$ARG"
        for ITEM in `get_items "$ARG"`; do
            if [ -d $PREFIX/"$ITEM" ]; then
                echo "mkdir -p $PREFIX/$ITEM"
                mkdir -p $PREFIX/"$ITEM"
            else
                echo "ln -s $STASHDIR/$ARG/$ITEM $PREFIX/$ITEM"
                ln -sf $STASHDIR/$ARG/"$ITEM" $PREFIX/"$ITEM"
            fi
        done
    done
}
OPTIONS=`getopt -- hr: "$@"` || exit 1
eval set -- "$OPTIONS"
while true; do
    case "$1" in
        -h) echo "stash -[hr:]"; shift;;
        -r) uninstall_package $2; shift 2;;
        --) shift; break;;
    esac
done
if [ $# -gt 0 ]; then
    install_package $@
else
    ls $STASHDIR
fi
